#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️  Styling your project before committing'

yarn lint --fix ||
(
  echo '❌ Hey! I think you ignoring my rules!
   ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

echo '✅  Great! Thats a good looking code!'