#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️  Styling and type-checking your project before committing'

npx --no-install lint-staged ||
(
  echo '❌ Hey! Something went wrong!
   Make the required changes listed above, add changes and try to commit again.'
  false;
)

echo '✅  Great! Thats a good looking code!'