name: Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deploy to Server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -rltgoDzvO --delete --exclude=".htaccess" --exclude=".well-known" --exclude=".htpasswds/" --exclude="cgi-bin/"
          path: src/
          remote_path: ${{ secrets.SSH_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}